-- Run this in the Supabase SQL Editor

-- 1. Create the 'secrets' table
create table if not exists secrets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  value text not null
);

-- 2. Disable Row Level Security (RLS) to allow public access for development
alter table secrets disable row level security;
